//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuaiexDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Display_Order { get; set; }
        public Nullable<decimal> DD_Rate { get; set; }
        public Nullable<decimal> TT_Rate { get; set; }
        public Nullable<decimal> TT_Min_Rate { get; set; }
        public string Status { get; set; }
        public Nullable<int> IsBaseCurrency { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedIp { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedIp { get; set; }
        public Nullable<System.Guid> UID { get; set; }
    }
}
