//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuaiexDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remittance_SubType_Mst
    {
        public int Remittance_SubType_Id { get; set; }
        public int Remittance_Type_Id { get; set; }
        public string Remittance_SubType { get; set; }
        public int Bank_Id { get; set; }
        public string English_Name { get; set; }
        public string Txn_Code1 { get; set; }
        public string Txn_Code2 { get; set; }
        public string Txn_Code3 { get; set; }
        public string Record_Status { get; set; }
        public string TT_Number_Prefix { get; set; }
    }
}
