//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuaiexDashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Count_Lookup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
